### ISSUE TITLE
Backport of performance monitoring for Cakephp 4.x

### ISSUE THREAD

**Issue by Harfusha** [LordSimal/cakephp-sentry#26]

**Comment by LordSimal** [comment]
Would you like to try backporting it or should I tackle that?

**Comment by Harfusha** [comment]
I dont have any experience with this repository. If you have time to backport it would be great :)

**Comment by Harfusha** [comment]
Any updates on this? Do you know any date you will have time for it? :)

**Comment by LordSimal** [comment]
Sorry, I am currently quite busy with other stuff, therefore I haven't had time backporting that.
Can't give you an ETA on that.

**Comment by LordSimal** [comment]
I can't make the performance monitoring feature work in CakePHP 4 due to the fact, that the Sentry Client only gets instantiated after an error or exception has been triggered, not while bootstrapping (which I do in newer versions)

But the PerformanceMiddleware requires, that the sentry client is already setup so that it can start a span while the middelware is being procesed. 

And trying to mangle that into the 1.x version of this plugin without breaking backwards compatibility is really something I don't want to do/try. I'd rather recommend upgrading to CakePHP 5.

You can check the [1.x-performance branch ](https://github.com/LordSimal/cakephp-sentry/tree/1.x-performance) if you want to, but it doesn't contain the change I described above. Only the parts of the rest of the performance monitoring feature.
